[package]
name = "tokenization-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
events = { path = "../../crates/events" }
infrastructure = { path = "../../crates/infrastructure" }
tokenization-orchestrator = { path = "../../crates/tokenization-orchestrator" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
